# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8427b7edf536abef0b20371b862cef3d91d4bf2991353d36f9ceaa58a5b07d8163b3e3f61f2022cfd3aaa9978ed982b546de85e327ca1afc325bfdd703e5f5c9

test:
  secret_key_base: aec402b2928ab4e77ec9be60aec3a03cdfff3ac4c608a344c3dfd8bb34e92b5642b46e26ffb5af1feb714ebc74e98158a48f43698b9c7de607cffefbdd401a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
